*** Found local files:
***   * /opt/airflow/logs/dag_id=hello_world/run_id=manual__2023-05-23T14:52:39+00:00/task_id=hello_task/attempt=1.log
[2023-05-23, 14:52:44 UTC] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_task manual__2023-05-23T14:52:39+00:00 [queued]>
[2023-05-23, 14:52:44 UTC] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_task manual__2023-05-23T14:52:39+00:00 [queued]>
[2023-05-23, 14:52:44 UTC] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-23, 14:52:44 UTC] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): hello_task> on 2023-05-23 14:52:39+00:00
[2023-05-23, 14:52:44 UTC] {standard_task_runner.py:57} INFO - Started process 70 to run task
[2023-05-23, 14:52:44 UTC] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'hello_task', 'manual__2023-05-23T14:52:39+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpammrxu2_']
[2023-05-23, 14:52:44 UTC] {standard_task_runner.py:85} INFO - Job 3: Subtask hello_task
[2023-05-23, 14:52:44 UTC] {task_command.py:410} INFO - Running <TaskInstance: hello_world.hello_task manual__2023-05-23T14:52:39+00:00 [running]> on host 70791099e2f0
[2023-05-23, 14:52:44 UTC] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='hello_world' AIRFLOW_CTX_TASK_ID='hello_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-23T14:52:39+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-23T14:52:39+00:00'
[2023-05-23, 14:52:44 UTC] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-23, 14:52:44 UTC] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "Hello Airflow (more like sh*tflow)"']
[2023-05-23, 14:52:44 UTC] {subprocess.py:86} INFO - Output:
[2023-05-23, 14:52:44 UTC] {subprocess.py:93} INFO - Hello Airflow (more like sh*tflow)
[2023-05-23, 14:52:44 UTC] {subprocess.py:97} INFO - Command exited with return code 0
[2023-05-23, 14:52:44 UTC] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_task, execution_date=20230523T145239, start_date=20230523T145244, end_date=20230523T145244
[2023-05-23, 14:52:44 UTC] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-05-23, 14:52:44 UTC] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check